// Code generated by ogen, DO NOT EDIT.

package gsn

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// StartRecording implements StartRecording operation.
//
// POST /api/v1/record/{login}
func (UnimplementedHandler) StartRecording(ctx context.Context, params StartRecordingParams) (r *StartRecordingOK, _ error) {
	return r, ht.ErrNotImplemented
}

// NewError creates *ErrorStatusCode from error returned by handler.
//
// Used for common default response.
func (UnimplementedHandler) NewError(ctx context.Context, err error) (r *ErrorStatusCode) {
	r = new(ErrorStatusCode)
	return r
}
