// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Recording struct {
	ID              pgtype.UUID
	Login           string
	CreatedAt       pgtype.Timestamp
	Ready           bool
	Title           string
	Category        string
	Language        string
	Viewers         int32
	StreamStartedAt pgtype.Timestamp
}
