version: "2"
sql:
  - engine: "postgresql"
    queries: "../internal/repository/queries/queries.sql"
    schema: "../internal/repository/migrations/"
    gen:
      go:
        package: "sqlc"
        out: "../internal/repository/sqlc"
        sql_package: "pgx/v5"